### ISSUE TITLE
dispatchGenericAqlPacket，If the size parameter in the function is not equal to 1, there may be problems.

### ISSUE THREAD

**Issue by hxxiaoming** [ROCm-Developer-Tools/clr#66]
while ((index - hsa_queue_load_read_index_scacquire(gpu_queue_)) >= sw_queue_size) {
    amd::Os::yield();
  }

 Here, it only checks if the ring buffer has an empty slot but does not determine how many empty slots are available. If the number of packets to be written is more than one, there may be a problem of overwriting packets that have not been processed yet.

**Comment by iassiour** [comment]
Thank you @hxxiaoming for reporting this issue. I will create an internal PR with a fix and update when it becomes available in develop branch.

**Comment by hxxiaoming** [comment]
Thanks iassiour!

**Comment by iassiour** [comment]
Hi @hxxiaoming as it turns out dispatching multiple packets is actually not fully supported so I have removed this option from dispatchGenericAqlPacket (i.e. size is now always equal to 1).

The change is in develop branch https://github.com/ROCm/clr/commit/d7f352dbed62c61390f8ddc363abb641964ad60c

I am closing this issue thank you for raising this.
